/** Shared demo payloads for Swagger "Try it out" and response examples. */

export const DEMO_UUID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
export const DEMO_UUID_2 = "b2c3d4e5-f6a7-8901-bcde-f12345678901";
export const DEMO_UUID_3 = "c3d4e5f6-a7b8-9012-cdef-123456789012";

export const examples = {
  admin: {
    adminId: DEMO_UUID,
    email: "admin@sangeetha.lk",
    fullName: "System Admin",
  },
  loginRequest: {
    email: "admin@sangeetha.lk",
    password: "admin123",
  },
  registerRequest: {
    name: "System Admin",
    email: "admin@sangeetha.lk",
    password: "admin123",
  },
  changePasswordRequest: {
    currentPassword: "admin123",
    newPassword: "newSecurePass1",
  },
  authTokenResponse: {
    success: true as const,
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example",
    admin: {
      adminId: DEMO_UUID,
      email: "admin@sangeetha.lk",
      fullName: "System Admin",
    },
  },
  supplier: {
    supplierId: DEMO_UUID,
    name: "Lanka Wax Supplies",
    contactNo: "+94771234567",
    email: "sales@lankawax.lk",
    address: "Colombo 10",
    isActive: true,
  },
  supplierRequest: {
    name: "Lanka Wax Supplies",
    contactNo: "+94771234567",
    email: "sales@lankawax.lk",
    address: "Colombo 10",
  },
  material: {
    materialId: DEMO_UUID,
    name: "Soy Wax",
    unit: "kg",
    quantityInStock: 25,
    reorderLevel: 10,
    supplierId: DEMO_UUID_2,
    supplierName: "Lanka Wax Supplies",
    isActive: true,
  },
  materialRequest: {
    name: "Soy Wax",
    unit: "kg",
    quantityInStock: 25,
    reorderLevel: 10,
    supplierId: DEMO_UUID_2,
  },
  product: {
    productId: DEMO_UUID,
    name: "Lavender Jar Candle",
    description: "200ml soy wax candle",
    price: 1500,
    stockQuantity: 40,
    category: "Jar Candles",
    imageUrl: "https://example.com/lavender.jpg",
    isActive: true,
  },
  productRequest: {
    name: "Lavender Jar Candle",
    description: "200ml soy wax candle",
    price: 1500,
    stockQuantity: 40,
    category: "Jar Candles",
    imageUrl: "https://example.com/lavender.jpg",
  },
  batchMaterial: {
    batchId: DEMO_UUID,
    materialId: DEMO_UUID_2,
    materialName: "Soy Wax",
    quantityUsed: 2.5,
    unit: "kg",
  },
  batch: {
    batchId: DEMO_UUID,
    productId: DEMO_UUID_3,
    productName: "Lavender Jar Candle",
    productionDate: "2026-07-01",
    quantityProduced: 20,
    status: "PLANNED" as const,
    materialsUsed: [
      {
        batchId: DEMO_UUID,
        materialId: DEMO_UUID_2,
        materialName: "Soy Wax",
        quantityUsed: 2.5,
        unit: "kg",
      },
    ],
    isActive: true,
  },
  batchRequest: {
    productId: DEMO_UUID_3,
    productionDate: "2026-07-01",
    quantityProduced: 20,
    status: "PLANNED" as const,
    materialsUsed: [{ materialId: DEMO_UUID_2, quantityUsed: 2.5 }],
  },
  customer: {
    customerId: DEMO_UUID,
    name: "Nimal Perera",
    phone: "+94771112233",
    email: "nimal@example.com",
    address: "Kandy",
    totalOrders: 3,
    isActive: true,
  },
  customerRequest: {
    name: "Nimal Perera",
    phone: "+94771112233",
    email: "nimal@example.com",
    address: "Kandy",
  },
  saleItem: {
    saleItemId: DEMO_UUID,
    saleId: DEMO_UUID_2,
    productId: DEMO_UUID_3,
    productName: "Lavender Jar Candle",
    quantity: 2,
    unitPrice: 1500,
  },
  sale: {
    saleId: DEMO_UUID_2,
    customerId: DEMO_UUID,
    customerName: "Nimal Perera",
    saleDate: "2026-07-10",
    totalAmount: 3000,
    status: "PENDING" as const,
    items: [
      {
        saleItemId: DEMO_UUID,
        saleId: DEMO_UUID_2,
        productId: DEMO_UUID_3,
        productName: "Lavender Jar Candle",
        quantity: 2,
        unitPrice: 1500,
      },
    ],
  },
  saleRequest: {
    customerId: DEMO_UUID,
    saleDate: "2026-07-10",
    status: "PENDING" as const,
    items: [{ productId: DEMO_UUID_3, quantity: 2, unitPrice: 1500 }],
  },
  employee: {
    employeeId: DEMO_UUID,
    name: "Kamal Silva",
    position: "PRODUCTION_STAFF" as const,
    phone: "+94770001122",
    salary: 65000,
    joinedDate: "2025-01-15",
    email: "kamal@sangeetha.lk",
    address: "Gampaha",
    isActive: true,
  },
  employeeRequest: {
    name: "Kamal Silva",
    position: "PRODUCTION_STAFF" as const,
    phone: "+94770001122",
    salary: 65000,
    joinedDate: "2025-01-15",
    email: "kamal@sangeetha.lk",
    address: "Gampaha",
  },
  attendance: {
    attendanceId: DEMO_UUID,
    employeeId: DEMO_UUID_2,
    employeeName: "Kamal Silva",
    date: "2026-07-16",
    status: "PRESENT" as const,
  },
  attendanceRequest: {
    employeeId: DEMO_UUID_2,
    date: "2026-07-16",
    status: "PRESENT" as const,
  },
  expense: {
    expenseId: DEMO_UUID,
    description: "Packaging materials",
    amount: 8500,
    expenseDate: "2026-07-05",
    category: "Operations",
    isActive: true,
  },
  expenseRequest: {
    description: "Packaging materials",
    amount: 8500,
    expenseDate: "2026-07-05",
    category: "Operations",
  },
  revenue: {
    revenueId: DEMO_UUID,
    saleId: DEMO_UUID_2,
    amount: 3000,
    receivedDate: "2026-07-11",
    isActive: true,
  },
  revenueRequest: {
    saleId: DEMO_UUID_2,
    amount: 3000,
    receivedDate: "2026-07-11",
  },
  statusRequest: {
    isActive: false,
  },
  financeSummary: {
    totalRevenue: 125000,
    totalExpenses: 42000,
    profit: 83000,
  },
  dashboardSummary: {
    productCount: 12,
    lowStockCount: 2,
    openBatches: 3,
    completedSalesCount: 45,
    totalRevenue: 125000,
    totalExpenses: 42000,
    profit: 83000,
    recentSales: [] as [],
    lowStockMaterials: [] as [],
  },
  inventoryReport: {
    products: [] as [],
    materials: [] as [],
  },
  pagination: {
    page: 1,
    pageSize: 10,
    totalItems: 1,
  },
  error: {
    success: false as const,
    message: "Resource not found",
  },
  message: {
    success: true as const,
    message: "Deleted successfully",
  },
};
